services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
      - model

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - model
    environment:
      MODEL_URL: "http://model:8000"

  model:
    build: ./model
    ports:
      - "8000:8000"
